# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='title',
            field=models.CharField(default='your_title', max_length=180),
            preserve_default=False,
        ),
    ]
